name: Deploying the project

on:
  push:
    branches: [ 'main' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node 20
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2
