name: Running the unit tests

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node 20
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
